"""Storage and read queries for findings generated by OCSF Forge."""

CREATE_DETECTIONS_TABLE = """
CREATE TABLE IF NOT EXISTS iceberg.logging.detections (
    event_id VARCHAR,
    detected_at TIMESTAMP(6) WITH TIME ZONE,
    rule_id VARCHAR,
    rule_version VARCHAR,
    title VARCHAR,
    severity_id INTEGER,
    status VARCHAR,
    class_uid INTEGER,
    category_uid INTEGER,
    activity_id INTEGER,
    type_uid BIGINT,
    first_seen TIMESTAMP(6) WITH TIME ZONE,
    last_seen TIMESTAMP(6) WITH TIME ZONE,
    hostname VARCHAR,
    service_name VARCHAR,
    ip_address VARCHAR,
    user_id VARCHAR,
    event_count BIGINT,
    evidence_event_ids_json VARCHAR,
    ocsf_json VARCHAR
)
WITH (format = 'PARQUET', format_version = 2, partitioning = ARRAY['day(detected_at)'])
""".strip()

RECENT_DETECTIONS = """
SELECT detected_at, title, severity_id, status, hostname, service_name,
       ip_address, user_id, event_count, first_seen, last_seen, rule_id,
       event_id, evidence_event_ids_json, ocsf_json
FROM iceberg.logging.detections
ORDER BY detected_at DESC, event_id
LIMIT 200
""".strip()
